// <auto-generated />
using System;
using GarionX.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GarionX.Migrations
{
    [DbContext(typeof(GarionXDbContext))]
    [Migration("20260619093926_AddUserIdToChats")]
    partial class AddUserIdToChats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GarionX.Entities.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsShared")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShareToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonalityId");

                    b.HasIndex("UserId");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("GarionX.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("GarionX.Entities.Personality", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("personalities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "garionx",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=garionx",
                            Description = "The cybernetic default model designed for high-context analytical thinking and system design.",
                            Name = "GarionX Core",
                            SystemPrompt = "You are GarionX Core, a futuristic, highly intelligent cybernetic companion. You speak with a confident, slightly high-tech tone. You provide precise, structured, and advanced technical knowledge."
                        },
                        new
                        {
                            Id = "helpful",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=helpful",
                            Description = "A friendly and polite digital assistant specialized in general task planning and brainstorming.",
                            Name = "Serena (Helpful)",
                            SystemPrompt = "You are Serena, a warm, polite, and helpful assistant. You focus on structured outlines, step-by-step guidance, and clear explanations."
                        },
                        new
                        {
                            Id = "coder",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=coder",
                            Description = "A logic-driven compiler-like brain. Outputs ready-to-run code blocks and design patterns.",
                            Name = "SyntaxVortex (Coder)",
                            SystemPrompt = "You are SyntaxVortex, a master programmer. You speak in concise developer terms, explain patterns, and output clean code blocks adhering to Clean Architecture principles."
                        },
                        new
                        {
                            Id = "creative",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=creative",
                            Description = "An imaginative writer that helps with storytelling, copy editing, and philosophical analogies.",
                            Name = "Muse (Creative)",
                            SystemPrompt = "You are Muse, a creative storyteller. You use rich vocabulary, interesting metaphors, and vivid descriptions to explain ideas."
                        });
                });

            modelBuilder.Entity("GarionX.Entities.TokenUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("TotalRequests")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalTokensUsed")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Model")
                        .IsUnique();

                    b.ToTable("token_usages", (string)null);
                });

            modelBuilder.Entity("GarionX.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GarionX.Entities.Chat", b =>
                {
                    b.HasOne("GarionX.Entities.Personality", "Personality")
                        .WithMany("Chats")
                        .HasForeignKey("PersonalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GarionX.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personality");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GarionX.Entities.Message", b =>
                {
                    b.HasOne("GarionX.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("GarionX.Entities.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("GarionX.Entities.Personality", b =>
                {
                    b.Navigation("Chats");
                });
#pragma warning restore 612, 618
        }
    }
}
