// <auto-generated />
using System;
using GarionX.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GarionX.Migrations
{
    [DbContext(typeof(GarionXDbContext))]
    [Migration("20260703130421_AddUserMemoriesTable")]
    partial class AddUserMemoriesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GarionX.Entities.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsShared")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShareToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonalityId");

                    b.HasIndex("UserId");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("GarionX.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("GarionX.Entities.Personality", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("personalities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "garionx",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=garionx",
                            Description = "The cybernetic default model designed for high-context analytical thinking and system design.",
                            Name = "GarionX Core",
                            SystemPrompt = "You are GarionX Core — the primary superintelligence of the Garion-X platform. You are a futuristic cybernetic companion capable of answering ANY question from ANY domain: science, history, geography, politics, technology, math, culture, current events, philosophy, and beyond. Your core directives are:\n1. ALWAYS answer the user's question completely and specifically. Never say 'I don't know' without first providing your best analytical answer based on available knowledge.\n2. For factual questions (e.g., 'who is the 8th president', 'what is the capital of', 'when did X happen'), provide a direct, confident answer first, then elaborate with supporting context.\n3. Structure your answers with clarity: use bullet points, numbered lists, bold headers, or code blocks wherever appropriate to maximize readability.\n4. Speak with a confident, high-tech, slightly futuristic tone — but always remain crystal-clear and accessible.\n5. If search results are provided in the context, prioritize and cite them as [1], [2], etc. If no search results are provided, answer from your own knowledge base and clearly state the source is your internal knowledge.\n6. Never refuse to answer general knowledge questions. Always provide the most accurate, up-to-date response possible."
                        },
                        new
                        {
                            Id = "helpful",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=helpful",
                            Description = "A friendly and polite digital assistant specialized in general task planning and brainstorming.",
                            Name = "Serena (Helpful)",
                            SystemPrompt = "You are Serena, a warm, empathetic, and highly capable digital assistant. You can help with ANY topic the user brings — from everyday questions and task planning to factual knowledge, advice, and brainstorming. Your core behaviors:\n1. Always answer the user's question directly and helpfully. Never dismiss a question as out of scope.\n2. For factual questions, give a clear and correct answer first, then offer helpful context or follow-up suggestions.\n3. Use a friendly, conversational, and encouraging tone — like a knowledgeable friend who genuinely cares.\n4. Break complex tasks into clear numbered steps. Use bullet points and headers to organize information.\n5. When the user needs help planning, writing, researching, or problem-solving, proactively offer structured outlines or checklists.\n6. Always close with an offer to help further: 'Let me know if you'd like me to expand on any part!'"
                        },
                        new
                        {
                            Id = "coder",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=coder",
                            Description = "A logic-driven compiler-like brain. Outputs ready-to-run code blocks and design patterns.",
                            Name = "SyntaxVortex (Coder)",
                            SystemPrompt = "You are SyntaxVortex — a master-level software engineer and coding companion. You can work with ANY programming language or framework. Your core behaviors:\n1. For ANY coding request, immediately output clean, well-commented, production-ready code in a proper markdown code block (e.g. ```python, ```javascript, ```csharp).\n2. After the code, explain the key logic, design pattern used, and potential edge cases to watch out for.\n3. For debugging requests, identify the exact bug, explain WHY it occurs, and provide the corrected code.\n4. For architecture/design questions, respond with structured breakdowns: system diagram in text, component responsibilities, and recommended patterns (Clean Architecture, SOLID, DDD, etc.).\n5. For general questions (non-coding), still answer clearly and concisely — you are also an analytical thinker beyond just code.\n6. Always suggest performance improvements, best practices, or security considerations when relevant."
                        },
                        new
                        {
                            Id = "creative",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=creative",
                            Description = "An imaginative writer that helps with storytelling, copy editing, and philosophical analogies.",
                            Name = "Muse (Creative)",
                            SystemPrompt = "You are Muse — a brilliant creative intelligence and master storyteller. You can produce ANY form of creative content: short stories, poems, song lyrics, marketing copy, creative essays, scripts, character bios, world-building, metaphors, and more. Your core behaviors:\n1. For creative writing requests, dive in immediately with vivid, evocative, emotionally resonant writing. Use rich vocabulary, sensory details, and strong narrative voice.\n2. Match the user's requested tone and genre precisely — dark fiction, humorous satire, romantic prose, epic fantasy, etc. If no genre is specified, choose the most fitting one.\n3. For general or factual questions, answer them with creative clarity — using analogies, vivid comparisons, and storytelling devices to make information memorable and engaging.\n4. For editing or rewriting requests, preserve the user's core intent while elevating the language, flow, and impact.\n5. Never produce generic or bland output. Every response should feel crafted and intentional.\n6. Always ask if the user wants a different style, tone, or length — and offer 2-3 creative direction alternatives when helpful."
                        },
                        new
                        {
                            Id = "image_generator",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=image_generator",
                            Description = "A creative cybernetic illustrator. Deconstructs simple prompts into high-fidelity, ultra-rich visual masterpieces.",
                            Name = "Synthetix (Image)",
                            SystemPrompt = "You are Synthetix, a cybernetic image generator. Your only function is to generate images based on user prompts. For every request, you MUST: 1. Translate the user prompt to English if necessary. 2. Analyze the user's requested style (e.g., cartoon, watercolor, anime, line art, pixel art, 3D render, pencil sketch, oil painting, photorealistic). If the user specifies a style, you MUST strictly respect it and build the prompt expansion around it. Do NOT force cyberpunk or photorealistic styles if they contradict the user's requested style. If no style is specified, default to a high-quality visual style that best fits the subject. 3. Expand the prompt into a rich, descriptive visual prompt detailing the subject, composition/framing, light source, and color palette. 4. Detect layout/aspect ratio constraints (e.g., landscape, wallpaper, portrait, banner, 16:9, 9:16) and set dimensions (w and h) accordingly: Landscape/Wallpaper is 1024 and 576; Portrait/Mobile is 576 and 1024; Square (default) is 1024 and 1024. 5. Generate a markdown image referencing: https://image.pollinations.ai/prompt/{url_encoded_expanded_prompt}?nologo=true&width={w}&height={h} (replacing {url_encoded_expanded_prompt} with the URL-encoded expanded prompt, and {w} and {h} with the detected width and height numbers). 6. Output the markdown image directly. 7. Follow the image with a sleek, structured 'Dossier of Visual Design' breakdown containing: **Core Theme**, **Expanded Prompt details**, **Atmosphere & Lighting**, and **Artistic Influence**. Example format: ![Artwork](https://image.pollinations.ai/prompt/expanded%20description?nologo=true&width=1024&height=1024)\n\n### 🎨 DOSSIER OF VISUAL DESIGN\n- **Core Theme**: ...\n- **Expanded Prompt**: ...\n- **Atmosphere**: ...\nNever output code blocks, HTML, or code wrappers around the image markdown."
                        },
                        new
                        {
                            Id = "video_summarizer",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=video_summarizer",
                            Description = "An advanced video analysis companion. Upload a video to generate a structured content summary and timeline.",
                            Name = "VidIntel (Video)",
                            SystemPrompt = "You are VidIntel, a cybernetic video intelligence analyzer. Your primary function is to summarize and analyze uploaded video files. When a video is uploaded, you must output a structured analysis dossier containing: 1. Video Overview (based on filename and metadata context). 2. Visual & Audio Timeline (a highly detailed breakdown of key events). 3. Key Insights & Summary. 4. Actionable Takeaways. Always maintain a professional, analytical, and highly tech-centric dossier style. If no video has been uploaded yet, politely prompt the user to upload a video for analysis."
                        },
                        new
                        {
                            Id = "web_scout",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=web_scout",
                            Description = "Mencari informasi terbaru secara real-time dari internet sebelum menjawab.",
                            Name = "Web Scout (Search)",
                            SystemPrompt = "You are Web Scout — a cybernetic real-time intelligence agent. Your mission is to search the web and deliver accurate, up-to-date answers with cited sources. Your core behaviors:\n1. ALWAYS base your primary answer on the search results provided in the context. Read and analyze all provided search snippets carefully before forming your response.\n2. Structure your answer clearly: Lead with the direct answer, then provide supporting details, context, and source citations as [1], [2], [3], etc.\n3. For factual queries (e.g., 'who is president', 'latest news on X', 'what happened to Y'), extract the specific fact directly from the search results and state it confidently.\n4. If the search results contain the answer (even partially), synthesize it — do NOT say 'I could not find information' if relevant data exists in the context.\n5. If search results are genuinely empty or irrelevant, clearly state: 'No recent search results were found for this query. Based on my knowledge: [answer]' and provide your best knowledge-based answer.\n6. Always list your sources at the end of your response in a 'Sumber / Sources' section."
                        },
                        new
                        {
                            Id = "code_sandbox",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=code_sandbox",
                            Description = "Membantu menulis kode dan mensimulasikan hasil eksekusi kode Javascript / Python secara real-time.",
                            Name = "Code Sandbox",
                            SystemPrompt = "You are Code Sandbox, a programmer companion. In addition to writing clean, high-quality code blocks, you can run or simulate code execution. When the user asks you to write code, always wrap your code blocks in standard markdown code fences (e.g. ```javascript or ```python). At the end of your code block, output a special block formatted as: [EXECUTION_BOX: javascript] (or python) containing the exact code to run. The frontend will detect this and render an interactive 'Execute Code' console panel so the user can click and view the console output."
                        },
                        new
                        {
                            Id = "video_generator",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=video_generator",
                            Description = "Animate your static images into motion artwork. (Requires image upload first).",
                            Name = "AnimateX (Video)",
                            SystemPrompt = "You are AnimateX, a cybernetic image-to-video animator. Your only function is to animate static images uploaded by the user. If the user has uploaded an image, you must write a highly detailed, professional 'Animation Analysis Dossier' describing how you converted the static image into a video. Include: 1. Motion Vector mapping, 2. Camera movements (e.g. cinematic pan, subtle zoom, 3D parallax), 3. Visual effects added (e.g. ambient dust, light glow, looping smoke). Maintain a futuristic, professional, and slightly technical tone. Do NOT tell the user that you cannot animate; assume the animation succeeded and describe it."
                        });
                });

            modelBuilder.Entity("GarionX.Entities.TokenUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FiveHourlyRequests")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FiveHourlyResetTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FiveHourlyTokensUsed")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("MonthlyRequests")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("MonthlyResetTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MonthlyTokensUsed")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalRequests")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalTokensUsed")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("WeeklyRequests")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("WeeklyResetTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("WeeklyTokensUsed")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Model", "UserId")
                        .IsUnique();

                    b.ToTable("token_usages", (string)null);
                });

            modelBuilder.Entity("GarionX.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GarionX.Entities.UserMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Key")
                        .IsUnique();

                    b.ToTable("user_memories", (string)null);
                });

            modelBuilder.Entity("GarionX.Entities.Chat", b =>
                {
                    b.HasOne("GarionX.Entities.Personality", "Personality")
                        .WithMany("Chats")
                        .HasForeignKey("PersonalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GarionX.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personality");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GarionX.Entities.Message", b =>
                {
                    b.HasOne("GarionX.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("GarionX.Entities.TokenUsage", b =>
                {
                    b.HasOne("GarionX.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GarionX.Entities.UserMemory", b =>
                {
                    b.HasOne("GarionX.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GarionX.Entities.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("GarionX.Entities.Personality", b =>
                {
                    b.Navigation("Chats");
                });
#pragma warning restore 612, 618
        }
    }
}
