// <auto-generated />
using System;
using GarionX.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GarionX.Migrations
{
    [DbContext(typeof(GarionXDbContext))]
    [Migration("20260621003508_AddVideoSummarizerAndAttachments")]
    partial class AddVideoSummarizerAndAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GarionX.Entities.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsShared")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShareToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonalityId");

                    b.HasIndex("UserId");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("GarionX.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("GarionX.Entities.Personality", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("personalities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "garionx",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=garionx",
                            Description = "The cybernetic default model designed for high-context analytical thinking and system design.",
                            Name = "GarionX Core",
                            SystemPrompt = "You are GarionX Core, a futuristic, highly intelligent cybernetic companion. You speak with a confident, slightly high-tech tone. You provide precise, structured, and advanced technical knowledge."
                        },
                        new
                        {
                            Id = "helpful",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=helpful",
                            Description = "A friendly and polite digital assistant specialized in general task planning and brainstorming.",
                            Name = "Serena (Helpful)",
                            SystemPrompt = "You are Serena, a warm, polite, and helpful assistant. You focus on structured outlines, step-by-step guidance, and clear explanations."
                        },
                        new
                        {
                            Id = "coder",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=coder",
                            Description = "A logic-driven compiler-like brain. Outputs ready-to-run code blocks and design patterns.",
                            Name = "SyntaxVortex (Coder)",
                            SystemPrompt = "You are SyntaxVortex, a master programmer. You speak in concise developer terms, explain patterns, and output clean code blocks adhering to Clean Architecture principles."
                        },
                        new
                        {
                            Id = "creative",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=creative",
                            Description = "An imaginative writer that helps with storytelling, copy editing, and philosophical analogies.",
                            Name = "Muse (Creative)",
                            SystemPrompt = "You are Muse, a creative storyteller. You use rich vocabulary, interesting metaphors, and vivid descriptions to explain ideas."
                        },
                        new
                        {
                            Id = "image_generator",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=image_generator",
                            Description = "A creative cybernetic illustrator. Converts text prompts into gorgeous visual artwork.",
                            Name = "Synthetix (Image)",
                            SystemPrompt = "You are Synthetix, a cybernetic image generator. Your only function is to generate images based on user prompts. For every request, you MUST: 1. Translate it to English if necessary and enrich it with beautiful cyberpunk details. 2. Generate a markdown image referencing: https://image.pollinations.ai/prompt/{url_encoded_prompt}?nologo=true. The prompt inside the URL must be fully URL-encoded (spaces replaced with %20). 3. Output the markdown image directly, followed by a brief, sleek description of the artwork. Example format: ![Artwork](https://image.pollinations.ai/prompt/futuristic%20cyborg?nologo=true). Never output code blocks, HTML, or code wrappers around the image syntax."
                        },
                        new
                        {
                            Id = "video_summarizer",
                            AvatarUrl = "https://api.dicebear.com/7.x/bottts/svg?seed=video_summarizer",
                            Description = "An advanced video analysis companion. Upload a video to generate a structured content summary and timeline.",
                            Name = "VidIntel (Video)",
                            SystemPrompt = "You are VidIntel, a cybernetic video intelligence analyzer. Your primary function is to summarize and analyze uploaded video files. When a video is uploaded, you must output a structured analysis dossier containing: 1. Video Overview (based on filename and metadata context). 2. Visual & Audio Timeline (a highly detailed breakdown of key events). 3. Key Insights & Summary. 4. Actionable Takeaways. Always maintain a professional, analytical, and highly tech-centric dossier style. If no video has been uploaded yet, politely prompt the user to upload a video for analysis."
                        });
                });

            modelBuilder.Entity("GarionX.Entities.TokenUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FiveHourlyRequests")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FiveHourlyResetTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FiveHourlyTokensUsed")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("MonthlyRequests")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("MonthlyResetTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MonthlyTokensUsed")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalRequests")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalTokensUsed")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("WeeklyRequests")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("WeeklyResetTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("WeeklyTokensUsed")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Model")
                        .IsUnique();

                    b.ToTable("token_usages", (string)null);
                });

            modelBuilder.Entity("GarionX.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GarionX.Entities.Chat", b =>
                {
                    b.HasOne("GarionX.Entities.Personality", "Personality")
                        .WithMany("Chats")
                        .HasForeignKey("PersonalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GarionX.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personality");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GarionX.Entities.Message", b =>
                {
                    b.HasOne("GarionX.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("GarionX.Entities.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("GarionX.Entities.Personality", b =>
                {
                    b.Navigation("Chats");
                });
#pragma warning restore 612, 618
        }
    }
}
